"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Pencil, Plus, Trash2 } from "lucide-react";
import Link from "next/link";
import { EmptyState } from "@/components/empty-state";
import { ErrorState } from "@/components/feedback/error-state";
import { PermissionDenied } from "@/components/feedback/permission-denied";
import { SeverityBadge } from "@/components/health/severity-badge";
import { PageHeader } from "@/components/page-header";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ProfileSelector } from "@/features/profiles/profile-selector";
import { useProfile } from "@/hooks/use-profile";
import { queryKeys } from "@/lib/query-keys";
import { allergyService } from "@/services/health-service";
import { ApiError } from "@/types/api";
import type { Allergy } from "@/types/health";

function DeleteAllergy({ allergy }: { allergy: Allergy }) { const client = useQueryClient(); const mutation = useMutation({ mutationFn: () => allergyService.remove(allergy.patient_id, allergy.id), onSuccess: () => void client.invalidateQueries({ queryKey: queryKeys.allergies(allergy.patient_id) }) }); return <AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" size="icon" aria-label={`Delete ${allergy.substance}`}><Trash2 className="size-4" /></Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete allergy record?</AlertDialogTitle><AlertDialogDescription>Delete the recorded item “{allergy.substance}”? This removes the Pathergy record, not a medical diagnosis.</AlertDialogDescription></AlertDialogHeader>{mutation.error ? <p role="alert" className="text-sm text-destructive">{mutation.error.message}</p> : null}<AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={(event) => { event.preventDefault(); mutation.mutate(); }}>Delete record</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>; }

export function AllergyList() { const { selected, selectedPatientId } = useProfile(); const query = useQuery({ queryKey: queryKeys.allergies(selectedPatientId!), queryFn: () => allergyService.list(selectedPatientId!), enabled: Boolean(selectedPatientId), gcTime: 60_000 }); const denied = query.error instanceof ApiError && query.error.code === "FAMILY_PERMISSION_DENIED"; return <><PageHeader title="Allergy records" description={`Manage recorded allergies for ${selected?.isOwn ? "your profile" : "the selected shared profile"}.`} actions={<Button asChild><Link href="/allergies/new"><Plus className="size-4" />Add allergy record</Link></Button>} /><ProfileSelector />{query.isLoading ? <p role="status">Loading allergy records…</p> : denied ? <PermissionDenied description="This profile has not shared allergy-view permission with you." /> : query.error ? <ErrorState message={query.error.message} onRetry={() => void query.refetch()} /> : !query.data?.length ? <EmptyState title="No allergy records have been added for this profile" description="An empty record list does not mean the person has no allergies." action={<Button asChild><Link href="/allergies/new">Add allergy record</Link></Button>} /> : <><div className="hidden md:block"><Table aria-label={`Allergy records for ${selected?.first_name ?? "selected profile"}`}><TableHeader><TableRow><TableHead>Substance</TableHead><TableHead>Reaction</TableHead><TableHead>Severity</TableHead><TableHead>RxCUI</TableHead><TableHead><span className="sr-only">Actions</span></TableHead></TableRow></TableHeader><TableBody>{query.data.map((allergy) => <TableRow key={allergy.id}><TableCell className="font-semibold">{allergy.substance}</TableCell><TableCell>{allergy.reaction ?? "Not recorded"}</TableCell><TableCell><SeverityBadge severity={allergy.severity} /></TableCell><TableCell>{allergy.rxcui ?? "—"}</TableCell><TableCell><div className="flex justify-end"><Button asChild variant="ghost" size="icon"><Link aria-label={`Edit ${allergy.substance}`} href={`/allergies/${allergy.id}/edit`}><Pencil className="size-4" /></Link></Button><DeleteAllergy allergy={allergy} /></div></TableCell></TableRow>)}</TableBody></Table></div><div className="grid gap-4 md:hidden">{query.data.map((allergy) => <Card key={allergy.id}><CardContent className="space-y-3 pt-6"><div className="flex items-start justify-between gap-3"><h2 className="font-bold">{allergy.substance}</h2><SeverityBadge severity={allergy.severity} /></div><p><span className="text-sm text-muted-foreground">Reaction:</span> {allergy.reaction ?? "Not recorded"}</p><p><span className="text-sm text-muted-foreground">RxCUI:</span> {allergy.rxcui ?? "Not recorded"}</p><div className="flex gap-2"><Button asChild variant="outline"><Link href={`/allergies/${allergy.id}/edit`}><Pencil className="size-4" />Edit</Link></Button><DeleteAllergy allergy={allergy} /></div></CardContent></Card>)}</div></>}</>; }
