"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import * as React from "react";
import { ErrorState } from "@/components/feedback/error-state";
import { useToast } from "@/components/feedback/toast-provider";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { useI18n } from "@/i18n/i18n-provider";
import { queryKeys } from "@/lib/query-keys";
import { familyService } from "@/services/family-service";
import type { EnforcedPermissionType } from "@/types/family";
const permissionTypes: EnforcedPermissionType[] = ["BASIC_PROFILE", "ALLERGIES", "SCREENING_HISTORY"];
type Values = Record<EnforcedPermissionType, { can_view: boolean; can_edit: boolean }>;
export function PermissionEditor({ groupId, userId }: { groupId: number; userId: number }) { const { t } = useI18n(); const client = useQueryClient(); const { notify } = useToast(); const query = useQuery({ queryKey: queryKeys.permissions(groupId, userId), queryFn: () => familyService.permissions(groupId, userId) }); const [draft, setDraft] = React.useState<Values | null>(null); const values = draft ?? Object.fromEntries(permissionTypes.map((type) => { const permission = query.data?.find((item) => item.data_type === type); return [type, { can_view: permission?.can_view ?? false, can_edit: permission?.can_edit ?? false }]; })) as Values; const mutation = useMutation({ mutationFn: () => familyService.updatePermissions(groupId, userId, permissionTypes.map((type) => ({ data_type: type, ...values[type] }))), onSuccess: (updated) => { client.setQueryData(queryKeys.permissions(groupId, userId), updated); setDraft(null); notify(t("permission.saved"), t("permission.savedDescription")); } }); function change(type: EnforcedPermissionType, field: "can_view" | "can_edit", checked: boolean) { setDraft({ ...values, [type]: { ...values[type], [field]: checked } }); } return <Card><CardHeader><CardTitle>{t("permission.title")}</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">{t("permission.description")}</p>{query.isLoading ? <p role="status">{t("permission.loading")}</p> : query.error ? <ErrorState message={query.error.message} onRetry={() => void query.refetch()} /> : <><div className="divide-y rounded-md border">{permissionTypes.map((type) => <fieldset key={type} className="grid gap-3 p-4 sm:grid-cols-[1fr_auto_auto]"><legend className="sr-only">{t(`permission.${type}`)}</legend><div><p className="font-semibold">{t(`permission.${type}`)}</p><p className="text-sm text-muted-foreground">{t(`permission.${type}.description`)}</p></div><label className="flex min-h-11 items-center gap-2"><Checkbox checked={values[type].can_view} onChange={(event) => change(type, "can_view", event.target.checked)} />{t("permission.canView")}</label><label className="flex min-h-11 items-center gap-2"><Checkbox checked={values[type].can_edit} onChange={(event) => change(type, "can_edit", event.target.checked)} />{t("permission.canEdit")}</label></fieldset>)}</div>{mutation.error ? <p role="alert" className="text-sm text-destructive">{mutation.error.message}</p> : null}<Button onClick={() => mutation.mutate()} disabled={!draft || mutation.isPending}>{mutation.isPending ? t("common.saving") : t("permission.save")}</Button></>}</CardContent></Card>; }
