"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import * as React from "react";
import { ErrorState } from "@/components/feedback/error-state";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { useToast } from "@/components/feedback/toast-provider";
import { queryKeys } from "@/lib/query-keys";
import { familyService } from "@/services/family-service";
import type { EnforcedPermissionType } from "@/types/family";
const types: Array<{ type: EnforcedPermissionType; label: string; description: string }> = [
  { type: "BASIC_PROFILE", label: "Basic profile", description: "Name and date of birth." },
  { type: "ALLERGIES", label: "Allergy records", description: "Recorded substances, reactions, severity, and optional RxCUI." },
  { type: "SCREENING_HISTORY", label: "Screening history", description: "Stored medication-check history. Edit permission allows a family medication check to create a record." },
];
type Values = Record<EnforcedPermissionType, { can_view: boolean; can_edit: boolean }>;
export function PermissionEditor({ groupId, userId }: { groupId: number; userId: number }) { const client = useQueryClient(); const { notify } = useToast(); const query = useQuery({ queryKey: queryKeys.permissions(groupId, userId), queryFn: () => familyService.permissions(groupId, userId) }); const [draft, setDraft] = React.useState<Values | null>(null); const values = draft ?? Object.fromEntries(types.map(({ type }) => { const permission = query.data?.find((item) => item.data_type === type); return [type, { can_view: permission?.can_view ?? false, can_edit: permission?.can_edit ?? false }]; })) as Values; const mutation = useMutation({ mutationFn: () => familyService.updatePermissions(groupId, userId, types.map(({ type }) => ({ data_type: type, ...values[type] }))), onSuccess: (updated) => { client.setQueryData(queryKeys.permissions(groupId, userId), updated); setDraft(null); notify("Sharing permissions saved", "These choices apply only to this family membership."); } }); function change(type: EnforcedPermissionType, field: "can_view" | "can_edit", checked: boolean) { setDraft({ ...values, [type]: { ...values[type], [field]: checked } }); } return <Card><CardHeader><CardTitle>My sharing permissions</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">These settings apply only to this family. OWNER and ADMIN roles do not override them.</p>{query.isLoading ? <p role="status">Loading sharing permissions…</p> : query.error ? <ErrorState message={query.error.message} onRetry={() => void query.refetch()} /> : <><div className="divide-y rounded-md border">{types.map((item) => <fieldset key={item.type} className="grid gap-3 p-4 sm:grid-cols-[1fr_auto_auto]"><legend className="sr-only">{item.label}</legend><div><p className="font-semibold">{item.label}</p><p className="text-sm text-muted-foreground">{item.description}</p></div><label className="flex min-h-11 items-center gap-2"><Checkbox checked={values[item.type].can_view} onChange={(event) => change(item.type, "can_view", event.target.checked)} />Can view</label><label className="flex min-h-11 items-center gap-2"><Checkbox checked={values[item.type].can_edit} onChange={(event) => change(item.type, "can_edit", event.target.checked)} />Can edit</label></fieldset>)}</div>{mutation.error ? <p role="alert" className="text-sm text-destructive">{mutation.error.message}</p> : null}<Button onClick={() => mutation.mutate()} disabled={!draft || mutation.isPending}>{mutation.isPending ? "Saving…" : "Save sharing permissions"}</Button></>}</CardContent></Card>; }
