"use client";
import { KeyRound, LogOut, MonitorSmartphone } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useAuth } from "@/hooks/use-auth";
import { formatDateTime } from "@/lib/format";
export function AccountSettings() { const { user, logout } = useAuth(); const router = useRouter(); async function signOut() { await logout(); router.replace("/login"); } return <><PageHeader title="Account settings" description="The current backend supports account summary, password security, sessions, and logout." /><Card><CardHeader><CardTitle>Account summary</CardTitle></CardHeader><CardContent><dl className="grid gap-4 sm:grid-cols-2"><div><dt className="text-sm text-muted-foreground">Display name</dt><dd className="font-semibold">{user?.display_name}</dd></div><div><dt className="text-sm text-muted-foreground">Email</dt><dd className="break-all font-semibold">{user?.email}</dd></div><div><dt className="text-sm text-muted-foreground">Email status</dt><dd><Badge>{user?.email_verified_at ? "Verified" : "Not verified"}</Badge>{user?.email_verified_at ? <span className="ml-2 text-sm">{formatDateTime(user.email_verified_at)}</span> : null}</dd></div><div><dt className="text-sm text-muted-foreground">Pathergy user ID</dt><dd className="font-semibold">{user?.user_id}</dd></div></dl><p className="mt-5 rounded-md bg-muted p-4 text-sm">Email and display name are read-only because the current backend does not provide an account-update endpoint.</p></CardContent></Card><Card><CardHeader><CardTitle>Security</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-3"><Button asChild variant="outline"><Link href="/change-password"><KeyRound className="size-4" />Change password</Link></Button><Button asChild variant="outline"><Link href="/security/sessions"><MonitorSmartphone className="size-4" />Active sessions</Link></Button><Button variant="destructive" onClick={() => void signOut()}><LogOut className="size-4" />Log out</Button></CardContent></Card></>; }
